### ISSUE TITLE
How do I use Subtitle instead of default title when sharing facebook?

### ISSUE THREAD

**Issue by kabeerTHanath** [benhuson/wp-subtitle#27] opened 2017-01-11 16:20 UTC
I use wp-subtitle for headings in my news blog, I use the actual title for getting SEO friendly url.  I need wp-subtitle for headings of the shared article on facebook.  How do I achieve it. Thankyou.

**Comment by benhuson** [comment] 2017-05-02 17:41
Duplicate of https://github.com/benhuson/wp-subtitle/issues/28

**Closed by benhuson** 2017-05-02 17:41 UTC
